name: yts_movies_redux
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  #firebase
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1

  freezed_annotation: ^0.14.3
  image_picker: ^0.8.2
  #dart
  redux_epics: ^0.15.0
  rxdart: ^0.27.1
  redux: ^5.0.0
  http: ^0.13.3
  built_value: ^8.1.1
  built_collection: ^5.1.0

  #flutter
  flutter_redux: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  freezed: ^0.14.3

dependency_overrides:
  analyzer: ^2.0.0
  meta: ^1.7.0
  rxdart: ^0.27.1

flutter:
  uses-material-design: true
  assets:
    - res/movies.json
